// Gifs animados por exercício (baixados de github.com/JahelCuadrado/ExerciseGymGifsDB)
module.exports = {
  "Supino Reto": "/exercicios/barbell-bench-press.gif",
  "Supino Inclinado": "/exercicios/barbell-incline-bench-press.gif",
  "Supino Declinado": "/exercicios/barbell-decline-bench-press.gif",
  "Crucifixo Reto": "/exercicios/dumbbell-fly.gif",
  "Crucifixo Inclinado": "/exercicios/dumbbell-incline-fly.gif",
  "Cross Over": "/exercicios/cable-cross-over-variation.gif",
  "Peck Deck": "/exercicios/lever-seated-fly.gif",
  "Supino Máq. Reto": "/exercicios/lever-chest-press.gif",
  "Supino Máq. Inclinado": "/exercicios/lever-incline-chest-press.gif",
  "Pull-over": "/exercicios/dumbbell-pullover.gif",
  "Desenvolvimento": "/exercicios/dumbbell-seated-shoulder-press.gif",
  "Desenv. Máquina": "/exercicios/lever-shoulder-press.gif",
  "Desenv. Arnold": "/exercicios/dumbbell-arnold-press.gif",
  "Elevação Lateral": "/exercicios/cable-lateral-raise.gif",
  "Elevação Frontal": "/exercicios/barbell-front-raise.gif",
  "Remada Alta": "/exercicios/barbell-upright-row.gif",
  "Encolhimento": "/exercicios/barbell-shrug.gif",
  "Pulley Tríceps": "/exercicios/cable-pushdown.gif",
  "Testa Polia": "/exercicios/cable-lying-triceps-extension-v-2.gif",
  "Testa Halter": "/exercicios/dumbbell-lying-triceps-extension.gif",
  "Frânces": "/exercicios/ez-bar-standing-french-press.gif",
  "Banco Tríceps": "/exercicios/bench-dip-knees-bent.gif",
  "Coice": "/exercicios/cable-standing-hip-extension.gif",
  "Supinado": "/exercicios/reverse-grip-machine-lat-pulldown.gif",
  "Corda Tríceps": "/exercicios/cable-pushdown-with-rope-attachment.gif",
  "Paralela": "/exercicios/chest-dip-on-straight-bar.gif",
  "Puxada p/ Trás": "/exercicios/cable-wide-grip-rear-pulldown-behind-neck.gif",
  "Puxada p/ Frente": "/exercicios/lever-front-pulldown.gif",
  "Remada Articulada": "/exercicios/lever-high-row.gif",
  "Remada Baixa": "/exercicios/cable-seated-row.gif",
  "Remada Curvada": "/exercicios/barbell-bent-over-row.gif",
  "Serrote": "/exercicios/kettlebell-one-arm-row.gif",
  "Peck Deck Invertido": "/exercicios/lever-seated-reverse-fly-parallel-grip.gif",
  "Crucifixo Inverso": "/exercicios/lever-seated-reverse-fly.gif",
  "Barra Fixa": "/exercicios/wide-grip-pull-up.gif",
  "Lombar": "/exercicios/lever-back-extension.gif",
  "Rosca Direta W": "/exercicios/ez-barbell-curl.gif",
  "Rosca Alternada": "/exercicios/dumbbell-alternate-biceps-curl.gif",
  "Rosca Scott Máq.": "/exercicios/lever-preacher-curl.gif",
  "Rosca Concentrada": "/exercicios/barbell-standing-concentration-curl.gif",
  "Rosca Polia Baixa": "/exercicios/cable-curl.gif",
  "Rosca Martelo": "/exercicios/dumbbell-cross-body-hammer-curl.gif",
  "Rosca 21": "/exercicios/barbell-curl.gif",
  "Rosca Scott": "/exercicios/barbell-preacher-curl.gif",
  "Banco Scott": "/exercicios/cable-preacher-curl.gif",
  "Rosca Inversa": "/exercicios/barbell-reverse-curl.gif",
  "Flexão de Punho": "/exercicios/barbell-wrist-curl.gif",
  "Extensão de Punho": "/exercicios/barbell-reverse-wrist-curl.gif",
  "Agachamento Hack": "/exercicios/barbell-hack-squat.gif",
  "Agachamento Smith": "/exercicios/smith-squat.gif",
  "Leg Press 45°": "/exercicios/sled-45-leg-press.gif",
  "Leg Press Horizontal": "/exercicios/lever-horizontal-one-leg-press.gif",
  "Avanço": "/exercicios/dumbbell-lunge.gif",
  "Extensor": "/exercicios/lever-leg-extension.gif",
  "Flexor Mesa": "/exercicios/lever-lying-leg-curl.gif",
  "Stiff": "/exercicios/dumbbell-stiff-leg-deadlift.gif",
  "Adutor": "/exercicios/lever-seated-hip-adduction.gif",
  "Abdutor": "/exercicios/lever-seated-hip-abduction.gif",
  "Cadeira Flexora": "/exercicios/lever-seated-leg-curl.gif",
  "Elevação Pélvica": "/exercicios/barbell-glute-bridge.gif",
  "Glúteo Máq. Artic.": "/exercicios/lever-hip-extension-v-2.gif",
  "Afundo": "/exercicios/barbell-lunge.gif",
  "Afundo com Step": "/exercicios/walking-lunge.gif",
  "Polia Glúteo": "/exercicios/cable-pull-through-with-rope.gif",
  "Panturrilha Smith": "/exercicios/smith-reverse-calf-raises.gif",
  "Panturrilha Solo": "/exercicios/bodyweight-standing-calf-raise.gif",
  "Panturrilha Sentada": "/exercicios/lever-seated-calf-raise.gif",
  "Panturrilha Leg Press": "/exercicios/sled-calf-press-on-leg-press.gif",
};
